### ISSUE TITLE
Example configurations

### ISSUE THREAD

**Issue by FaFre** [waymarkedtrails/waymarkedtrails-api#1]
I'm interested to see how your solution of the route overlay works. It took me a long time now to get my machine configured to get the planet imported correctly.

@lonvia is it possible that you provide a sample `wmt_db.config.*` and `wmt_api.config.*` file and where to store them?

Thank you very much!

**Comment by FaFre** [comment]
Maybe I should ask it right away, does my database look correct and ready to use with the api?

```
planet=# \dt
               List of relations
 Schema |        Name        | Type  |  Owner   
--------+--------------------+-------+----------
 public | country_osm_grid   | table | postgres
 public | node_changeset     | table | postgres
 public | nodes              | table | postgres
 public | relation_changeset | table | postgres
 public | relations          | table | postgres
 public | spatial_ref_sys    | table | postgres
 public | status             | table | postgres
 public | way_changeset      | table | postgres
 public | ways               | table | postgres
```

**Comment by lonvia** [comment]
I'm not sure what you mean. The configuration in the repos should work out of the box. You can add a `waymarkedtrails-backend/wmt_db/config/local.py` to overwrite settings in `waymarkedtrails-backend/wmt_db/config/common.py` (same format). The configuration in `waymarkedtrails-api/config` still needs editing in each file. Please be aware that the separated repos are still work in progress and I need to find a free weekend to make them production ready (including writing proper READMEs).

You only show the data in the pulbic schema in your database. You find the data for the route maps in schemas (hiking, cycling, ...).

**Comment by FaFre** [comment]
EDIT: I linked the wmt_db folder from *-backend and it works work now!
Thank you!

**Comment by lonvia** [comment]
These are standard python modules, so PYTHONPATH is your friend:

```
export PYTHONPATH=.:~/dev/waymarkedtrails-shields:~/dev/waymarkedtrails-backend:~/dev/osgende

uwsgi --plugin python3 --py-auto-reload 1 --socket 127.0.0.1:8080 --protocol=http --wsgi-file frontend.py
```
