### ISSUE TITLE
Search by area not working

### ISSUE THREAD

**Issue by Juanjo-MC** [waymarkedtrails/waymarkedtrails-api#2]
Hi,

it seems that search by area is not working, it doesn't return any result, no matter the provided bbox.

https://hiking.waymarkedtrails.org/api/v1/list/by_area?bbox=-10.437,44.119,3.582,35.764
https://hiking.waymarkedtrails.org/api/v1/list/by_area?bbox=-10.437,35.764,3.582,44.119

**Comment by lonvia** [comment]
The by_area call expects coordinates in WebMercator (3857).

**Comment by Juanjo-MC** [comment]
much better indeed ;-)
Thank you lonvia
