### ISSUE TITLE
hug/falcon `not JSON serializable` error mitigation

### ISSUE THREAD

**Issue by waterced** [waymarkedtrails/waymarkedtrails-api#6]
Hi!

I am trying to install my own WMT local instance to play around with rendering, etc. I'm facing troubles with the API.

When calling the API, I face the following error. `TypeError: ('Type[ujson] is not Serializable', TypeError('<wmt_api.output.route_item.DetailedRouteItem object at 0x7f0487d4e920> is not JSON serializable'))` I found out it is a well known hug/falcon error, which can be mitigated with
```
@hug.startup()
def init_settings(api):
    api.http.falcon.req_options.auto_parse_qs_csv = False
```
And indeed, I found this included in the `[frontend.py](https://github.com/waymarkedtrails/waymarkedtrails-api/blob/master/wmt_api/frontend.py)` of the api. However it looks like this `init_settings(api)` function is not run. Am I missing something?

Thanks for your help,

PS: I'm launching the api with `uwsgi --plugin python3 --virtualenv wmtenv --py-auto-reload 1 --socket 127.0.0.1:8080 --protocol=http --wsgi wmt_api.frontend`, I added the virtualenv option.

**Comment by lonvia** [comment]
Make sure you don't have ujson installed or set the environment variable HUG_USE_UJSON to the empty string (i.e. `export HUG_USE_UJSON=`).

**Comment by waterced** [comment]
Indeed, setting the environment variable HUG_USE_UJSON to the empty string worked. Thanks for your help!

**Comment by lonvia** [comment]
I've added a hint in the README.
