### ISSUE TITLE
`Access window out of range in RasterIO()` error when working with elevation

### ISSUE THREAD

**Issue by waterced** [waymarkedtrails/waymarkedtrails-api#7]
Hi,
In my attempt to setup my own WMT, I've been looking into elevation data. I figured out how to configure the `DEM_FILE`. For testing I downloaded [this](https://land.copernicus.eu/imagery-in-situ/eu-dem/eu-dem-v1.1?tab=download&selected:list=dem-v1-1-e40n20) DEM model from eu copernicus. However I'm facing issue when calling the API in french Savoie region, with a `Access window out of range in RasterIO().  Requested (-131292,-109909) of size 1263x1513 on raster of 40000x40000.` error.
The issue seems quite clear, the ` band_array = self.source.GetRasterBand(1).ReadAsArray(ulx, uly,
                                                              lrx - ulx + 1,
                                                              lry - uly + 1) ` from `Dem` class (`elevation.py`) is called with negative values.

Which makes me wonder whether the `geo_to_pixel` function is well defined. Was it tested on several DEM files? What DEM are you using on [waymarkedtrails.org](waymarkedtrails.org)?
Btw, it might help to know that the the GeoTransform of the DEM I'm using is:
 ```python
>>> source.GetGeoTransform()
(4000000.0, 25.0, 0.0, 3000000.0, 0.0, -25.0)
```
Thanks in advance for your help,

**Comment by waterced** [comment]
More details : 
About My DEM file : 
```
source.GetProjectionRef()
'PROJCS["ETRS89_ETRS_LAEA",GEOGCS["ETRS89",DATUM["European_Terrestrial_Reference_System_1989",SPHEROID["GRS 1980",6378137,298.257222101004,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6258"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4258"]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["latitude_of_center",52],PARAMETER["longitude_of_center",10],PARAMETER["false_easting",4321000],PARAMETER["false_northing",3210000],UNIT["metre",1],AXIS["Easting",EAST],AXIS["Northing",NORTH]]'
```
```
source.GetGCPProjection()
(4000000.0, 25.0, 0.0, 3000000.0, 0.0, -25.0)
```
About the region I am considering, its `bbox` retrieve by WMT-api is `(717654.1592876037, 5709959.199253561, 749219.1348605087, 5747770.799570954)`. Looks like these coords do are not include in the DEM region, which whould trigger the error mentioned. Yet I am certain that the DEM cover this region... Different coordonates system?

**Comment by lonvia** [comment]
The whole code is tested exactly against one DEM, the one we use. It was originally prepared by Yves from OpenSnowMap.

You certainly have the wrong projection in your file. It needs to be EPSG:3857. There used to be some information on the former wiki, which I copy here for your convenience. Maybe it helps:

===

To show elevation profiles in Waymarked Trails you need a digital elevation model (DEM). Near global DEMs with a useful resolution and accuracy are [SRTM](https://www2.jpl.nasa.gov/srtm/) and [ASTER](https://asterweb.jpl.nasa.gov/gdem.asp). In following we assume you use geoTIFF files from ASTER.

After downloading the area you need to reproject all the tiles to Spherical Mercator projection, which is the projection used on Waymarked Trails. We use [GDAL](http://www.gdal.org/) for this:

    gdalwarp -s_srs EPSG:4326 -t_srs EPSG:900913 old.tif new.tif

(see [gdal.org](http://gdal.org/gdalwarp.html))

After reprojecting all images you might want to merge the files together to one file:

    ls -1 *.tif > tiff_list.txt
    gdal_merge.py -v -o merged_image.tif --optfile tiff_list.txt

Make sure you don't merge the images to files larger then 200-500 Mb.

Finally you need to add the result files to a virtual file:

    gdalbuildvrt DEM.vrt *.tif

The vrt files together with all the tif files should reside in the same directory and the vrt file needs to be referenced from the ELEVATION_PROFILE_DEM setting.

**Comment by waterced** [comment]
Thank you very much, this is really helpful, everything is running fine now :)
