### ISSUE TITLE
Wrong elevation profile for route with alternative

### ISSUE THREAD

**Issue by pyrog** [waymarkedtrails/waymarkedtrails-api#9]
[GR 3](https://hiking.waymarkedtrails.org/#route?id=2704569&type=relation) have 12 stages. The last is an alternative.

The elevation profile have 3 segments (see [Knooppuntnet](https://knooppuntnet.nl/fr/monitor/groups/fr-nwn/routes/GR%203/map?mode=osm-segments&reference=false&matches=false&deviations=false&osm-relation=true&selected-deviation=0&selected-osm-segment=2&position=47.42925001,-2.20754408,12)) but logically alternatives, excursions… shouldn't be rendered on the profile and the API should return one continuous segment.

The following message "Route is potentially unordered or incomplete. Elevation information might be inaccurate." is displayed too by the frontend.

Also, the mapped length is 1329 km, but the elevation profile x axis show more than 2500 km.

<img width="50%" alt="Green copy" src="https://github.com/waymarkedtrails/waymarkedtrails-api/assets/2158081/88178a9d-731a-4f80-8138-f66071294d6c">

**Comment by lonvia** [comment]
Roles in routes are not supported yet. This is already tracked in https://github.com/waymarkedtrails/waymarked-trails-site/issues/356 and https://github.com/waymarkedtrails/waymarked-trails-site/issues/179

**Comment by mgorfer** [comment]
What is the recommended way to enter routes with roles? 
I am just creating a new route, which originally has excursions and alternatives and approaches.
Is it still best to use them in OSM, or create different routes for the different roles?

https://www.openstreetmap.org/relation/9741603
https://www.herz-ass-villgratental.at/wanderweg

**Comment by lonvia** [comment]
Please use the roles as described in the wiki. waymarkedtrails will get support for it eventually.
